# Generated by Django 4.0.3 on 2022-03-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangowikidata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=200),
        ),
    ]
