# Generated by Django 4.0.3 on 2022-03-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangowikidata', '0002_person_address_alter_person_surname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
