# Generated by Django 4.0.3 on 2022-03-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangowikidata', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
