# Generated by Django 4.0.3 on 2022-03-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangowikidata', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='wd_records',
            field=models.ManyToManyField(related_name='wd_records', to='djangowikidata.wdrecord'),
        ),
    ]
