# Generated by Django 3.2.13 on 2022-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_course_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', max_length=500),
        ),
    ]
